name: SSH Remote Command

on:
  push:
    branches:
      - main  # change to 'master' if your repo uses that

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run commands on remote server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "✅ Connected to remote server!"
            hostname
            uptime
            whoami
